name = "FreeRegistry"
uuid = "541705df-369b-4b86-be5f-0cd910f78608"
repo = "https://github.com/GHTaarn/FreeRegistry"

[packages]
1d60e3b1-536a-4e4e-a637-1f588248ba8b = { name = "History", path = "H/History" }
5ca6e7c4-69d2-49cf-b3ce-e6fbf50f8d91 = { name = "InfiniteSets", path = "I/InfiniteSets" }
7d5ddd29-585a-4ccb-ac42-b8c514ef29f6 = { name = "SimpleUI", path = "S/SimpleUI" }
b1b94250-c2ee-4735-b5f7-9deb07899968 = { name = "TerminalFilePicker", path = "T/TerminalFilePicker" }
